name: aoc2025
description: Max Korbel's Solutions for Advent of Code 2025 using ROHD
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.2

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  path: ^1.9.0
  rohd: ^0.6.6
  rohd_hcl: ^0.2.1
  rohd_vf: ^0.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

dependency_overrides:
  rohd:
    git:
      url: https://github.com/intel/rohd.git
      ref: main